### ISSUE TITLE
4bit kernel error when large input size

### ISSUE THREAD

**Issue by Tracin** [mit-han-lab/llm-awq#7]
` import torch
import f16s4_gemm
in_features = 14336
out_features = 5376                                                                                                                
w = torch.Tensor(in_features, out_features // (32 // 4)).to(torch.int32).cuda()
scales = torch.Tensor(in_features // 128, out_features).half().cuda()
qzeros = torch.Tensor(in_features // 128, out_features // (32 // 4)).to(torch.int32).cuda()
x = torch.Tensor(2048 * 8, 14336).cuda().half()                                                                                                                                                        
f16s4_gemm.gemm_forward_cuda(x, w, scales, qzeros, 8)`
when m of gemm is 2048 x 8, it runs perfectly, if we double it 
`x = torch.Tensor(2048 * 16, 14336).cuda().half()`
I got an error like `RuntimeError: CUDA error: invalid configuration argument`
I think my GPU memory is sufficient since I ran this on A100.

**Comment by ys-2020** [comment]
Hi @Tracin! Thanks a lot for bringing the issue to our attention. We have fixed the problem in #8 , please have a look! Once again, thank you for your interest in AWQ.

**Comment by Tracin** [comment]
Hi @ys-2020! Very appreciated for your MR for this. It is very impressive both the AWQ method and this fast kernel.
However I am afraid there is still something wrong in it. When I continue doubling the M up to `2048 * 32`, I met a `CUDA error: an illegal memory access was encountered`.
I believe you understand it is 32 batchsize and 2k sentence length which is quite often used for LLM inference.

**Comment by ys-2020** [comment]
Hi @Tracin , we have reproduced the illegal memory access issue and are trying to fix it. Please stay tuned for our updates. Thanks!

**Comment by jamesdborin** [comment]
I got this error today as well for long generation. Do you know what the issue is, and if there is a patch / fix we can do locally?

Thanks!
